JZ-main/LL/myproject/beer/urls.py
from django.urls import path
from . import views

app_name = 'beer'
urlpatterns = [
    path('ver2_select', views.ver2_select, name='ver2_select'),
    path('ver2_session', views.ver2_session, name='ver2_session'),
    path('ver3_select', views.ver3_select, name='ver3_select'),
    path('ver3_session', views.ver3_session, name='ver3_session'),
    path('purpose', views.purpose, name='purpose'),
    path('review', views.review, name='review'),
]

JZ-main/LL/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.views.generic import RedirectView

# API viewset
from rest_framework import routers
from beer import views
# from register import views
# from django.views.generic import ProductView

# class HomeTemplateView(ProductView):
#     template_name = 'index.html'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('/', include('beer.urls')),
    path('', RedirectView.as_view(url="/home", permanent=True)),
    path('user/', include('user.urls')),
    path('like/', include('like.urls')),
    # path('', include('register.urls')),
    # path('', HomeTemplateView.as_view(), name='home'),
]

JZ-main/LL/myproject/user/urls.py
from django.urls import path
from . import views

# http://logalhost/user
app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

JZ-main/LL/myproject/beer/views.py
from django.shortcuts import render, redirect
from django.db import transaction
from django.core.paginator import Paginator

from django.contrib.auth.decorators import login_required
from django.core.serializers.json import DjangoJSONEncoder
import json
from django.http import HttpResponse, request, response

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import mean_squared_error
from sklearn.impute import SimpleImputer
import sklearn as sk
import warnings
# 직렬화
from rest_framework import viewsets
import csv
import random

from .models import *

from django.conf import settings
from user.models import *
from django.urls import reverse

warnings.filterwarnings('ignore')

# def add_cart(request):
#     # 요청파라미터 조회
#     # 같은 이름으로 여러 개 값이 넘어오는 경우 getlist('name')으로 조회
#     item_list = request.POST.getlist('item')
#     # 요청파라미터 검증
#     if not item_list:  # item을 선택하지 않고 요청했을 때
#         return render(request, 'beer/ver_session.html',
#                       {"error_message": "상품을 선택하세요"})

#     # 카트를 dictionary로 생성해서 session에 저장
#     # 카트를 session에서 조회
#     cart = request.session.get('cart')
#     if not cart:
#         cart = request.session['cart'] = {}
#         # cart = {}
#         # request.session['cart'] = cart

#     for item in item_list:
#         # 없으면 추가, 있으면 value를 1 증가
#         cnt = cart.get(item)
#         if cnt:  # 카트에 있는 제품인 경우
#             cart[item] = cnt + 1
#         else:
#             cart[item] = 1
#     print(cart[item])
#     # 장바구니 조회 페이지로 이동
#     return redirect(reverse('cart:cart_list'))


# 우리가 예측한 평점과 실제 평점간의 차이를 MSE로 계산
def get_mse(pred, actual):
    # 평점이 있는 실제 영화만 추출
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)


# 특정 도시와 비슷한 유사도를 가지는 도시 Top_N에 대해서만 적용 -> 시간오래걸림
def predict_rating_topsim(ratings_arr, item_sim_arr, n=20):
    # 사용자-아이템 평점 행렬 크기만큼 0으로 채운 예측 행렬 초기화
    pred = np.zeros(ratings_arr.shape)

    # 사용자-아이템 평점 행렬의 도시 개수만큼 루프
    for col in range(ratings_arr.shape[1]):
        # 유사도 행렬에서 유사도가 큰 순으로 n개의 데이터 행렬의 인덱스 반환
        top_n_items = [np.argsort(item_sim_arr[:, col])[:-n - 1:-1]]
        # 개인화된 예측 평점 계산 : 각 col 도시별(1개), 2496 사용자들의 예측평점
        for row in range(ratings_arr.shape[0]):
            pred[row, col] = item_sim_arr[col, :][top_n_items].dot(
                ratings_arr[row, :][top_n_items].T)
            pred[row, col] /= np.sum(item_sim_arr[col, :][top_n_items])

    return pred


def get_not_tried_beer(ratings_matrix, userId):
    # userId로 입력받은 사용자의 모든 도시 정보를 추출해 Series로 반환
    # 반환된 user_rating은 영화명(title)을 인덱스로 가지는 Series 객체
    user_rating = ratings_matrix.loc[userId, :]

    # user_rating이 0보다 크면 기존에 관란함 영화.
    # 대상 인덱스를 추출해 list 객체로 만듦
    tried = user_rating[user_rating > 0].index.tolist()

    # 모든 도시명을 list 객체로 만듦
    beer_list = ratings_matrix.columns.tolist()

    # list comprehension으로 tried에 해당하는 도시는 beer_list에서 제외
    not_tried = [beer for beer in beer_list if beer not in tried]

    return not_tried


# 예측 평점 DataFrame에서 사용자 id 인덱스와 not_tried로 들어온 도시명 추출 후
# 가장 예측 평점이 높은 순으로 정렬


def recomm_beer_by_userid(pred_df, userId, not_tried, top_n):
    recomm_beer = pred_df.loc[userId,
                              not_tried].sort_values(ascending=False)[:top_n]
    return recomm_beer


def recomm_feature(df):

    ratings = df[['장소', '아이디', '평점']]
    # 피벗 테이블을 이용해 유저-아이디 매트릭스 구성
    ratings_matrix = ratings.pivot_table('평점', index='아이디', columns='장소')
    ratings_matrix.head(3)

    # fillna함수를 이용해 Nan처리
    ratings_matrix = ratings_matrix.fillna(0)

    # 유사도 계산을 위해 트랜스포즈
    ratings_matrix_T = ratings_matrix.transpose()

    # 아이템-유저 매트릭스로부터 코사인 유사도 구하기
    item_sim = cosine_similarity(ratings_matrix_T, ratings_matrix_T)

    # cosine_similarity()로 반환된 넘파이 행렬에 영화명을 매핑해 DataFrame으로 변환
    item_sim_df = pd.DataFrame(data=item_sim,
                               index=ratings_matrix.columns,
                               columns=ratings_matrix.columns)

    return item_sim_df


def recomm_beer(item_sim_df, beer_name):
    # 해당 도시와 유사도가 높은 도시 5개만 추천
    return item_sim_df[beer_name].sort_values(ascending=False)[1:10]


def recomm_detail(item_sim_df, detail):
    # 해당 도시와 유사도가 높은 도시 5개만 추천
    return item_sim_df[detail].sort_values(ascending=False)[1:10]


# 선택한 관광지 세션 저장
def ver2_select(request):
    beer_list = pd.read_csv('result.csv', encoding='utf-8', index_col=0)

    beer_list = beer_list['locate']

    text = {'beer_list': beer_list}

    login_session = request.session.get('login_session')

    if login_session == '':
        text['login_session'] = False
    else:
        text['login_session'] = True

    if request.method == 'POST':
        beer_name = request.POST.get('beer', '')
        request.session['tour'] = beer_name
        text['tour'] = request.session['tour']

    return render(request, 'beer/ver2.html', text)


def purpose(request):
    beer_list = pd.read_csv('result.csv', encoding='utf-8', index_col=0)

    beer_list = beer_list['locate']

    text = {'beer_list': beer_list}

    login_session = request.session.get('login_session')

    if login_session == '':
        text['login_session'] = False
    else:
        text['login_session'] = True

    if request.method == 'POST':
        locate = request.POST.get('locate', 0)
        family = int(request.POST.get('family', 0))
        reports = int(request.POST.get('reports', 0))
        history = int(request.POST.get('history', 0))
        themepark = int(request.POST.get('themepark', 0))
        food = int(request.POST.get('food', 0))
        arts = int(request.POST.get('arts', 0))
        heeling = int(request.POST.get('heeling', 0))
        city = int(request.POST.get('city', 0))
        nature = int(request.POST.get('nature', 0))

        purpose = [
            locate,
            family,
            reports,
            history,
            themepark,
            food,
            arts,
            heeling,
            city,
            nature,
        ]
        print(purpose)

        # purpose_data = Survey(locate=locate,
        #                       reports=reports,
        #                       history=history,
        #                       themepark=themepark,
        #                       food=food,
        #                       heeling=heeling,
        #                       family=family,
        #                       arts=arts,
        #                       city=city,
        #                       nature=nature)
        purpose_data = Survey(
            locate=locate,
            family=family,
            reports=reports,
            history=history,
            themepark=themepark,
            food=food,
            arts=arts,
            heeling=heeling,
            city=city,
            nature=nature,
        )

        purpose_data.save()

    return render(request, 'beer/ver1.html', text)


def review(request):
    beer_list = pd.read_csv('result.csv', encoding='utf-8', index_col=0)

    beer_list = beer_list['locate']

    text = {'beer_list': beer_list}

    login_session = request.session.get('login_session')

    if login_session == '':
        text['login_session'] = False
    else:
        text['login_session'] = True

    if request.method == 'POST':
        locate = request.POST.get('locate', 0)
        review_star = request.POST.get('reviewStar', 0)
        review_body = request.POST.get('review_body', 0)

        review = (locate, review_star, review_body)

        review_data = Review2(locate=locate,
                              review_star=review_star,
                              review_body=review_body)

        print(review)

        review_data.save()

    return render(request, 'beer/ver1.html', text)


# @login_required
# def add_cart(request, product_pk):
#     # 상품을 담기 위해 해당 상품 객체를 product 변수에 할당
#     product = Hotel.objects.get(pk=product_pk)

#     try:
#         # 장바구니는 user 를 FK 로 참조하기 때문에 save() 를 하기 위해 user 가 누구인지도 알아야 함
#         cart = HotelCart.objects.get(product__id=hotel.pk,
#                                      user__id=request.user.pk)
#         if cart:
#             if cart.product.name == product.name:
#                 cart.quantity += 1
#                 cart.save()
#     except CartItem.DoesNotExist:
#         user = User.objects.get(pk=request.user.pk)
#         cart = CartItem(
#             user=user,
#             product=product,
#             quantity=1,
#         )
#         cart.save()
#     return redirect('%2Fver2_session')


# 세션에 저장된 관광지 가져와 계산
def ver2_session(request):
    ratings = pd.read_csv('merge.csv', encoding='utf-8', index_col=0)
    cluster_3 = pd.read_csv('대표군집클러스터링.csv', encoding='utf-8', index_col=0)
    cluster_all = pd.read_csv('전체도시클러스터링.csv', encoding='utf-8', index_col=0)

    # 세션 데이터 가져오기
    beer_name = request.session.get('tour')

    # 관광지 추천
    df = recomm_feature(ratings)

    result = recomm_beer(df, beer_name)
    result = result.index.tolist()

    # 로그인 세션 유지
    login_session = request.session.get('login_session')

    if login_session == '':
        request.session['login_session'] = False
    else:
        request.session['login_session'] = True

    # 숙박 시설 필터
    cost = request.GET.get('cost', '')
    sort = request.GET.get('sort', '')
    rating = request.GET.get('rating', '')
    rating1 = request.GET.get('rating1', '')
    distance = request.GET.get('distance', '')
    review = request.GET.get('review', '')

    if rating == 'rating':
        content_list = Hotel.objects.filter(
            place=result[0]).order_by('-rating')

    elif distance == 'distance':
        content_list = hotel1_distance_up = Hotel.objects.filter(
            place=result[0]).order_by('distance')

    elif cost == 'cost_down':
        content_list = Hotel.objects.filter(place=result[0]).order_by('-cost')

    elif cost == 'cost_up':

JZ-main/LL/myproject/beer/templates/beer/ver1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
        integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <link rel="stylesheet" href={% static 'css/reset.css' %}>
    <link rel="icon"type="image/x-icon" href={% static 'favicon/favicon.ico' %}>
    <meta charset="UTF-8">
    <title>경험기반추천</title>
    <style>
        h1 {
            text-align: center;
            color: black;
        }

        h3 {
            text-align: center;
            color: white;
        }

        img {
            display: block;
            margin: 0px auto;
            width: 80%;
            height: 70%;
            border-radius: 3vw;
        }

        select {
            width: 200px;
            padding: .5em .5em;
            border: 1px solid #999;
            font-family: inherit;
            background: url('arrow.jpg') no-repeat 95% 50%;
            border-radius: 0px;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
        }

        input[type=text] {
            width: 190px;
            height: 30px;
            font-size: 20px;
        }

        body {
            display: block;
            background-image:url("{% static 'mg/ver1.jpg' %}");
            background-size: 100% 200%;
            background-color: #f8f8ff;
        }

        h1 {
            text-align: center;
            font-size: 2.5vw;
            padding-left: 4%;
            padding-right: 4%;
        }
    </style>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6672621543823482"crossorigin="anonymous">
    </script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
     </script>
</head>

<body>
    <div class="nav-comtain">
        <nav>
            <a href="/">HOME</a>
            <a href="{% url 'beer:ver2_select'%}">EXPERIENCE</a>
            <a href="{% url 'beer:ver3_select'%}">THEME</a>
            {% if login_session%}
            <a href="{% url 'user:logout' %}"><button class="logout-btn">LOGOUT</button></a>
            {% else %}
            <a href="{% url 'user:login' %}"><button class="login-btn">LOGIN</button></a>
            <a href="{% url 'user:register' %}"><button class="join-btn">JOIN</button></a>
            {% endif %}
            <div id="indicator"></div>
        </nav>
    </div>
    <br />
    <div class="header">
        <a class="header-a" onclick="location.href='/'">너와 나드리</a>
    </div>
    <div class="ver1-contain" >
        <form method="POST" id="ver1-form" action="{% url 'beer:purpose'%}">
          {% csrf_token %}
            <div class="ques-1">
              <div class="form-qeus">어디를 방문했나요?</div>
              <select class="ver3-destination-detail" name="locate">
                {% for tmp in beer_list %}
                <option value='{{tmp}}'>{{tmp}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="ques-2">
              <div class="form-qeus">어떤 목적으로 방문했나요?</div>
              <div class="ver1-survey-contain">
                <label class="form-label"><input onclick="CountChecked(this)" type="checkbox" name="family"
                        value=1><span>가족</span></style>
                <br>
                <label class="form-label"><input onclick="CountChecked(this)" type="checkbox" name="history"
                        value=1><span>역사</span></label>
                <br>
                <label class="form-label"><input onclick="CountChecked(this)" type="checkbox" name="reports"
                        value=1><span>레포츠</span></label>
                <label class="form-label"><input onclick="CountChecked(this)" type="checkbox" name="themepark"
                        value=1><span>테마파크</span></label>
                <br>
                <label class="form-label"><input onclick="CountChecked(this)" type="checkbox" name="food"
                        value=1><span>먹방</span></label>
                <label class="form-label"><input onclick="CountChecked(this)" type="checkbox" name="arts"
                        value=1><span>예술</span></label>
                <label class="form-label"><input onclick="CountChecked(this)" type="checkbox" name="heeling"
                        value=1><span>휴식</span></label>
                <br>
                <label class="form-label"><input onclick="CountChecked(this)" type="checkbox" name="city"
                        value=1><span>도심</span></label>
                <label class="form-label"><input onclick="CountChecked(this)" type="checkbox" name="nature"
                        value=1><span>자연</span></label>
                <br>
              </div>
            </div>
            <input type="submit" value="완 료 하 기">
        </form>
    </div>
    <div class="ver1-review-contain">
      <form method="POST" class="review-form" action="{% url 'beer:review' %}">
        {% csrf_token %}
        <div class="ques-1">
          <div class="form-qeus">어디를 방문했나요?</div>
          <select class="ver3-destination-detail" name="locate">
            {% for tmp in beer_list %}
            <option value='{{tmp}}'>{{tmp}}</option>
            {% endfor %}
          </select>
        </div>
        <fieldset>
          <span class="text-bold">별점을 선택해주세요</span>
          <input type="radio" name="reviewStar" value="5" id="rate5"><label for="rate5">★</label>
          <input type="radio" name="reviewStar" value="4" id="rate4"><label for="rate4">★</label>
          <input type="radio" name="reviewStar" value="3" id="rate3"><label for="rate3">★</label>
          <input type="radio" name="reviewStar" value="2" id="rate2"><label for="rate2">★</label>
          <input type="radio" name="reviewStar" value="1" id="rate1"><label for="rate1">★</label>
        </fieldset>
        <div>
          <textarea class="col-auto form-control" type="text" id="reviewContents" name="review_body"
                placeholder="좋은 리뷰를 남겨주시면 포인트를 적립해드립니다 ! !"></textarea>
        </div>
        <input type="submit" value="완 료 하 기" />	
      <form>

    </div>
    <div id='contents' style="text-align:center; opacity:0.5; background-color:#F5F5F5; padding-top:10%;">
        <img id="mg1" src="static/mg/airplane2.jpg">
    </div>
    </div>

    <ins class="adsbygoogle"
     style="display:block; z-index:1000;"
     data-ad-format="autorelaxed"
     data-ad-client="ca-pub-6672621543823482"
     data-ad-slot="2683442818">
    </ins>

    <footer class="footer" style="margin-top:5vh;">
        <div class="footer-addr">
          <div style="text-align:left">
            <a class="footer-logo" onclick="location.href='/'">너와 나드리</a>
          </div>
          <h2>Contact</h2>
          
          <address>
            <div style="text-align:left">
                <a href="https://www.google.com/maps/place/%EC%A4%91%EB%B6%80%EB%8C%80%ED%95%99%EA%B5%90+%EA%B3%A0%EC%96%91%EC%BA%A0%ED%8D%BC%EC%8A%A4+%E4%B8%AD%E9%83%A8%E5%A4%A7%E5%AD%B8%E6%A0%A1+Joongbu+University/data=!4m5!3m4!1s0x357c943e1caccd2b:0x56404200ca89df47!8m2!3d37.713203!4d126.8900751">
                    중부대학교 창의캠퍼스. 세종관 828호
                </a><br>
            </div>
                
            <a class="footer-btn">문의하기</a>
          </address>
        </div>
        
        <ul class="footer-p">
          <li class="p-item">
            <h2 class="p-title">너와 나드리</h2>
      
            <ul class="p-ul">
              <li>
                <p>김병찬</p>
              </li>
      
              <li>
                <p>정욱채</p>
              </li>
                  
              <li>
                <p>한정우</p>
              </li>
            </ul>
          </li>
          
          <li class="p-item">
            <h2 class="p-title">사용기술</h2>
            
            <ul class="p-ul">
              <li>
                <p>경험기반 추천받기</p>
              </li>
              
              <li>
                <p>테마기반 추천받기</p>
              </li>
              
              <li>
                <p>세션기반 추천받기</p>
              </li>
            </ul>
          </li>
          
          <li class="p-item">
            <h2 class="p-title">지도교수</h2>
            
            <ul class="p-ul">
              <li>
                <p>김송강 교수</p>
              </li>
              
              <li>
                <p>황호진 교수</p>
              </li>
              
            </ul>
          </li>
        </ul>
        
        <div class="footer-sub">
          <div class="sub-name">
            <p>&copy; 2022 정보통신학과. 졸업작품 프로젝트.</p>
          </div>
        </div>
    </footer>
</body>

</html>

JZ-main/LL/myproject/beer/templates/beer/ver2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
        integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <link rel="stylesheet" href={% static 'css/reset.css' %}>
    <meta charset="UTF-8">
    <title>경험기반추천</title>
    <style>
        h1 {
            text-align: center;
            color: black;
        }

        h3 {
            text-align: center;
            color: white;
        }

        img {
            display: block;
            margin: 0px auto;
            width: 80%;
            height: 70%;
            border-radius: 3vw;
        }

        select {
            width: 200px;
            padding: .5em .5em;
            border: 1px solid #999;
            font-family: inherit;
            background: url('arrow.jpg') no-repeat 95% 50%;
            border-radius: 0px;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
        }

        input[type=text] {
            width: 190px;
            height: 30px;
            font-size: 20px;
        }

        body {
            display: block;
            background-image:url("{% static 'mg/ver1.jpg' %}");
            background-size: 100% 200%;
            background-color: #f8f8ff;
        }

        h1 {
            text-align: center;
            font-size: 2.5vw;
            padding-left: 4%;
            padding-right: 4%;
        }
    </style>
</head>

<body>
    <div class="nav-comtain">
        <nav>
            <a href="/">HOME</a>
            <a href="{% url 'beer:ver2_select'%}">EXPERIENCE</a>
            <a href="{% url 'beer:ver3_select'%}">THEME</a>
            {% if login_session%}
            <a href="{% url 'user:logout' %}"><button class="logout-btn">LOGOUT</button></a>
            {% else %}
            <a href="{% url 'user:login' %}"><button class="login-btn">LOGIN</button></a>
            <a href="{% url 'user:register' %}"><button class="join-btn">JOIN</button></a>
            {% endif %}
            <div id="indicator"></div>
        </nav>
    </div>
    <br />
    <div class="header">
        <a class="header-a" onclick="location.href='/'">너와 나드리</a>
    </div>
    <div class="ver2-contain">
        <h1 style="padding-top:3%;">경험했던 여행지 중 다시 가고싶은 여행지를 선택해주세요.
            비슷한 여행지를 추천해 드립니다.    
        </h1>
        <form method="POST" style="text-align:center;"onsubmit="goData();">
            <br>
            {% csrf_token %}

            여행지 :
            <select name="beer" style="margin-top:5%">
                {% for tmp in beer_list %}
                <option value='{{tmp}}'>{{tmp}}</option>
                {% endfor %}


                </button>
                {% comment %} <input class="btn-submit" type="submit" value="Pick!" onClick="location.href={% url 'beer:ver2_session' %}"> {% endcomment %}
            </select>
            <input class="btn-submit" type="submit" value="Pick!" alret="성공">
            <a href="{% url 'beer:ver2_session'%}">다음 페이지 이동</a>

        </form>
    </div>

    <div id='contents' style="text-align:center; opacity:0.5; background-color:#F5F5F5; padding-top:10%;">
        <img id="mg1" src="static/mg/airplane2.jpg">
    </div>
    </div>
    <footer class="footer" style="margin-top:5vh;">
        <div class="footer-addr">
            <div style="text-align:left">
                <a class="footer-logo" onclick="location.href='/'">너와 나드리</a>
            </div>
            <h2>Contact</h2>

            <address>
                <div style="text-align:left">
                    <a
                        href="https://www.google.com/maps/place/%EC%A4%91%EB%B6%80%EB%8C%80%ED%95%99%EA%B5%90+%EA%B3%A0%EC%96%91%EC%BA%A0%ED%8D%BC%EC%8A%A4+%E4%B8%AD%E9%83%A8%E5%A4%A7%E5%AD%B8%E6%A0%A1+Joongbu+University/data=!4m5!3m4!1s0x357c943e1caccd2b:0x56404200ca89df47!8m2!3d37.713203!4d126.8900751">
                        중부대학교 창의캠퍼스. 세종관 828호
                    </a><br>
                </div>

                <a class="footer-btn">문의하기</a>
            </address>
        </div>

        <ul class="footer-p">
            <li class="p-item">
                <h2 class="p-title">너와 나드리</h2>

                <ul class="p-ul">
                    <li>
                        <p>김병찬</p>
                    </li>

                    <li>
                        <p>정욱채</p>
                    </li>

                    <li>
                        <p>한정우</p>
                    </li>
                </ul>
            </li>

            <li class="p-item">
                <h2 class="p-title">사용기술</h2>

                <ul class="p-ul">
                    <li>
                        <p>경험기반 추천받기</p>
                    </li>

                    <li>
                        <p>테마기반 추천받기</p>
                    </li>

                    <li>
                        <p>세션기반 추천받기</p>
                    </li>
                </ul>
            </li>

            <li class="p-item">
                <h2 class="p-title">지도교수</h2>

                <ul class="p-ul">
                    <li>
                        <p>김송강 교수</p>
                    </li>

                    <li>
                        <p>황호진 교수</p>
                    </li>

                </ul>
            </li>
        </ul>

        <div class="footer-sub">
            <div class="sub-name">
                <p>&copy; 2022 정보통신학과. 졸업작품 프로젝트.</p>
            </div>
        </div>
    </footer>
</body>

</html>